apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jb2d
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-jb2d@sha256:fcf8ad7569e8da92f2f97353930bcfbaaf2413df197b5c189c53fb658b91c867
        name: my-nodejs
        resources: {}
status: {}
